/*==========================================================================
 |   Source code:  FibSequence.java
 |        Author:  Dylan Sumler
 |    Student ID:  3538998
 |    Assignment:  Assignment #6 - Fibonacci sequence
 |
 |        Course:  COP 3337 (Programming II)
 |       Section:  U02
 |    Instructor:  William Feild
 |      Due Date:  20 April 2017, class time
 |
 |	I hereby certify that this collective work is my own
 |	and none of it is the work of any other person or entity.
 |	______________________________________ [Signature]
 |
 |      Language:  Java
 |   Compile/Run:
 |
 |
 |  +-----------------------------------------------------------------------
 |
 |  Description:  This class implements the next method in the sequence class
 |                and determines the next number in the Fibonacci sequence
 |                recursively.
 |
 |        Input:  No input is used for this class.
 |
 |       Output:  No output is generated by this class.
 |
 |      Process:  A FibSequence object is created and the next method is
 |                called to generate the next number of the sequence. The next
 |                method calls the fibCalc method which determines the nth
 |                number of the sequence where n is a parameter for fibCalc.
 |
 |   Required Features Not Included:   All required features are included.
 |
 |
 |   Known Bugs:  None; the program operates as intended.
 |  *======================================================================*/


public class FibSequence implements Sequence{

   private int currentValue = 0;       //current value in the sequence

   /**
   *  Default constructor
   */
   FibSequence(){}

   /**
   *  Gets the current index of the sequence.
   *  @return The current index of the sequence.
   */
   public int getCurrent(){
      return currentValue;
   }

   /**
   *  Sets the current index of the sequence.
   *  @param value The updated index of the sequence.
   */
   public void setCurrent(int value){
      currentValue = value;
   }

   /**
   *  Calculates the next number in the Fibonacci sequence.
   *  @return The next number in the sequence.
   */
   private int fibCalc(int number){
      if(number <= 1)
         return 1;
      else
         return fibCalc(number - 1) + fibCalc(number - 2);
   }

   /**
   *  Implements the next method of the sequence interface.
   *  @return The next value of the sequence.
   */
   @Override
   public int next(){
      return fibCalc(currentValue);
   }
}
